name: Docker Image CI

on:
  release:
    types: [published]
  push:
    branches:
      - ci
    tags:
      - v*

env:
  IMAGE_NAME: kybber/traefik-domeneshop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        run: |
          echo ${{ github.event_name}}
          echo ${{ github.event}}
          echo ${{ github.event_path}}
