name: Docker Image CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]
  tags: 
    - v*

env:
  IMAGE_NAME: kybber/traefik-domeneshop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        if: ${{ github.event_name != "tags" }}
        run: docker build . --file Dockerfile

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        if: ${{ github.event_name == "tags" }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: $IMAGE_NAME
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
